(function(){/*
 http://google-maps-utility-library-v3.googlecode.com
 -- Nianwei Liu [nianwei at gmail dot dom]
*/
var f=Math.PI/180,g=0,h=window;h.ags_jsonp=h.ags_jsonp||{};var j=google.maps,k,l,n,o={O:null,L:false},p={},q={};function r(a,c,b){var d=c===""?0:a.indexOf(c);return a.substring(d+c.length,b===""?a.length:a.indexOf(b,d+c.length))}function s(){j.event.trigger.apply(this,arguments)}
function u(){if(typeof XMLHttpRequest==="undefined"){try{return new ActiveXObject("Msxml2.XMLHTTP.6.0")}catch(a){}try{return new ActiveXObject("Msxml2.XMLHTTP.3.0")}catch(c){}try{return new ActiveXObject("Msxml2.XMLHTTP")}catch(b){}throw new Error("This browser does not support XMLHttpRequest.");}else return new XMLHttpRequest}var v="esriGeometryPoint",w="esriGeometryMultipoint",x="esriGeometryPolyline",y="esriGeometryPolygon",z="esriGeometryEnvelope";
function A(a){var c=a;if(a&&a.splice&&a.length>0)c=a[0];if(c instanceof j.LatLng||c instanceof j.Marker)return a&&a.splice&&a.length>1?w:v;else if(c instanceof j.Polyline)return x;else if(c instanceof j.Polygon)return y;else if(c instanceof j.LatLngBounds)return z;else if(c.x!==undefined&&c.y!==undefined)return v;else if(c.W)return w;else if(c.V)return x;else if(c.X)return y;return null}
function B(a){var c=a;if(a&&a.splice&&a.length>0)c=a[0];if(c&&c.splice&&c.length>0)c=c[0];if(c instanceof j.LatLng||c instanceof j.Marker||c instanceof j.Polyline||c instanceof j.Polygon||c instanceof j.LatLngBounds)return true;return false}function D(a,c){for(var b=[],d,e=0,i=a.getLength();e<i;e++){d=a.getAt(e);b.push("["+d.lng()+","+d.lat()+"]")}c&&b.length>0&&b.push("["+a.getAt(0).lng()+","+a.getAt(0).lat()+"]");return b.join(",")}
function E(a){var c;if(typeof a==="object")if(a&&a.splice){c=[];for(var b=0,d=a.length;b<d;b++)c.push(E(a[b]));return"["+c.join(",")+"]"}else if(B(a)){var e;d="{";switch(A(a)){case v:e=a&&a.splice?a[0]:a;if(e instanceof j.Marker)e=e.getPosition();d+="x:"+e.lng()+",y:"+e.lat();break;case w:b=[];for(c=0;c<a.length;c++){e=a[c]instanceof j.Marker?a[c].getPosition():a[c];b.push("["+e.lng()+","+e.lat()+"]")}d+="points: ["+b.join(",")+"]";break;case x:b=[];a=a&&a.splice?a:[a];for(c=0;c<a.length;c++)b.push("["+
D(a[c].getPath())+"]");d+="paths:["+b.join(",")+"]";break;case y:b=[];e=a&&a.splice?a[0]:a;a=e.getPaths();for(c=0;c<a.getLength();c++)b.push("["+D(a.getAt(c),true)+"]");d+="rings:["+b.join(",")+"]";break;case z:e=a&&a.splice?a[0]:a;d+="xmin:"+e.getSouthWest().lng()+",ymin:"+e.getSouthWest().lat()+",xmax:"+e.getNorthEast().lng()+",ymax:"+e.getNorthEast().lat();break}d+=", spatialReference:{wkid:4326}";d+="}";return d}else if(a.toJSON)return a.toJSON();else{c="";for(b in a)if(a.hasOwnProperty(b)){if(c.length>
0)c+=", ";c+=b+":"+E(a[b])}return"{"+c+"}"}return a.toString()}function F(a){var c="";if(a){a.R=a.R||"json";for(var b in a)if(a.hasOwnProperty(b)&&a[b]!==null&&a[b]!==undefined){var d=E(a[b]);c+=b+"="+(escape?escape(d):encodeURIComponent(d))+"&"}}return c}
function G(a,c,b,d){var e="ags_jsonp"+g++ +"_"+Math.floor(Math.random()*1E6),i=null;c=F(c);c+=(b||"callback")+"=ags_jsonp."+e;var C=document.getElementsByTagName("head")[0];if(!C)throw new Error("document must have header tag");h.ags_jsonp[e]=function(){delete h.ags_jsonp[e];i&&C.removeChild(i);i=null;d.apply(null,arguments);s(q,"jsonpend",e)};if((c+a).length<2E3&&!o.L){i=document.createElement("script");i.src=a+(a.indexOf("?")===-1?"?":"&")+c;i.id=e;C.appendChild(i)}else{b=window.location;b=b.protocol+
"//"+b.hostname+(!b.port||b.port===80?"":":"+b.port+"/");var t=true;if(a.toLowerCase().indexOf(b.toLowerCase())!==-1)t=false;if(o.L)t=true;if(t&&!o.O)throw new Error("No proxyUrl property in Config is defined");var m=u();m.onreadystatechange=function(){if(m.readyState===4)if(m.status===200)eval(m.responseText);else throw new Error("Error code "+m.status);};m.open("POST",t?o.O+"?"+a:a,true);m.setRequestHeader("Content-Type","application/x-www-form-urlencoded");m.send(c)}s(q,"jsonpstart",e);return e}
q.getJSON=function(a,c,b,d){G(a,c,b,d)};q.addToMap=function(a,c){if(c&&c.splice)for(var b,d=0,e=c.length;d<e;d++)if((b=c[d])&&b.splice)q.addToMap(a,b);else B(b)&&b.setMap(a)};q.removeFromMap=function(a,c){q.addToMap(null,a);if(c)a.length=0};function H(a){a=a||{};this.v=a.v;this.J=a.J}H.prototype.forward=function(a){return a};H.prototype.inverse=function(a){return a};H.prototype.m=function(){return 360};H.prototype.toJSON=function(){return"{"+(this.v?" wkid:"+this.v:"wkt: '"+this.J+"'")+"}"};
function I(a){a=a||{};H.call(this,a)}I.prototype=new H;function J(a){a=a||{};H.call(this,a);var c=a.D,b=a.H*f,d=a.I*f,e=a.F*f;this.a=a.s/a.u;this.e=a.n*f;this.g=a.B;this.h=a.C;a=1/c;c=2*a-a*a;this.d=Math.sqrt(c);a=this.i(b,c);c=this.i(d,c);e=K(this,e,this.d);b=K(this,b,this.d);d=K(this,d,this.d);this.b=Math.log(a/c)/Math.log(b/d);this.z=a/(this.b*Math.pow(b,this.b));this.f=this.l(this.a,this.z,e,this.b)}J.prototype=new H;
J.prototype.i=function(a,c){var b=Math.sin(a);return Math.cos(a)/Math.sqrt(1-c*b*b)};function K(a,c,b){a=b*Math.sin(c);return Math.tan(Math.PI/4-c/2)/Math.pow((1-a)/(1+a),b/2)}J.prototype.l=function(a,c,b,d){return a*c*Math.pow(b,d)};J.prototype.k=function(a,c,b){b=c*Math.sin(b);return Math.PI/2-2*Math.atan(a*Math.pow((1-b)/(1+b),c/2))};J.prototype.G=function(a,c,b){var d=0;b=b;for(var e=this.k(a,c,b);Math.abs(e-b)>1.0E-9&&d<10;){d++;b=e;e=this.k(a,c,b)}return e};
J.prototype.forward=function(a){var c=a[0]*f;a=this.l(this.a,this.z,K(this,a[1]*f,this.d),this.b);c=this.b*(c-this.e);return[this.g+a*Math.sin(c),this.h+this.f-a*Math.cos(c)]};J.prototype.inverse=function(a){var c=a[0]-this.g,b=a[1]-this.h;a=Math.atan(c/(this.f-b));c=Math.pow((this.b>0?1:-1)*Math.sqrt(c*c+(this.f-b)*(this.f-b))/(this.a*this.z),1/this.b);return[(a/this.b+this.e)/f,this.G(c,this.d,Math.PI/2-2*Math.atan(c))/f]};J.prototype.m=function(){return Math.PI*2*this.a};
function L(a){a=a||{};H.call(this,a);this.a=a.s/a.u;var c=a.D;this.p=a.T;var b=a.F*f;this.e=a.n*f;this.g=a.B;this.h=a.C;a=1/c;this.c=2*a-a*a;this.o=this.c*this.c;this.A=this.o*this.c;this.j=this.c/(1-this.c);this.K=this.i(b,this.a,this.c,this.o,this.A)}L.prototype=new H;L.prototype.i=function(a,c,b,d,e){return c*((1-b/4-3*d/64-5*e/256)*a-(3*b/8+3*d/32+45*e/1024)*Math.sin(2*a)+(15*d/256+45*e/1024)*Math.sin(4*a)-35*e/3072*Math.sin(6*a))};
L.prototype.forward=function(a){var c=a[1]*f,b=a[0]*f;a=this.a/Math.sqrt(1-this.c*Math.pow(Math.sin(c),2));var d=Math.pow(Math.tan(c),2),e=this.j*Math.pow(Math.cos(c),2);b=(b-this.e)*Math.cos(c);var i=this.i(c,this.a,this.c,this.o,this.A);return[this.g+this.p*a*(b+(1-d+e)*Math.pow(b,3)/6+(5-18*d+d*d+72*e-58*this.j)*Math.pow(b,5)/120),this.h+this.p*(i-this.K)+a*Math.tan(c)*(b*b/2+(5-d+9*e+4*e*e)*Math.pow(b,4)/120+(61-58*d+d*d+600*e-330*this.j)*Math.pow(b,6)/720)]};
L.prototype.inverse=function(a){var c=a[0],b=a[1];a=(1-Math.sqrt(1-this.c))/(1+Math.sqrt(1-this.c));b=(this.K+(b-this.h)/this.p)/(this.a*(1-this.c/4-3*this.o/64-5*this.A/256));a=b+(3*a/2-27*Math.pow(a,3)/32)*Math.sin(2*b)+(21*a*a/16-55*Math.pow(a,4)/32)*Math.sin(4*b)+151*Math.pow(a,3)/6*Math.sin(6*b)+1097*Math.pow(a,4)/512*Math.sin(8*b);b=this.j*Math.pow(Math.cos(a),2);var d=Math.pow(Math.tan(a),2),e=this.a/Math.sqrt(1-this.c*Math.pow(Math.sin(a),2)),i=this.a*(1-this.c)/Math.pow(1-this.c*Math.pow(Math.sin(a),
2),1.5);c=(c-this.g)/(e*this.p);e=a-e*Math.tan(a)/i*(c*c/2-(5+3*d+10*b-4*b*b-9*this.j)*Math.pow(c,4)/24+(61+90*d+28*b+45*d*d-252*this.j-3*b*b)*Math.pow(c,6)/720);return[(this.e+(c-(1+2*d+b)*Math.pow(c,3)/6+(5-2*b+28*d-3*b*b+8*this.j+24*d*d)*Math.pow(c,5)/120)/Math.cos(a))/f,e/f]};L.prototype.m=function(){return Math.PI*2*this.a};function M(a){a=a||{};H.call(this,a);this.a=(a.s||6378137)/(a.u||1);this.e=(a.n||0)*f}M.prototype=new H;
M.prototype.forward=function(a){var c=a[1]*f;return[this.a*(a[0]*f-this.e),this.a/2*Math.log((1+Math.sin(c))/(1-Math.sin(c)))]};M.prototype.inverse=function(a){return[(a[0]/this.a+this.e)/f,(Math.PI/2-2*Math.atan(Math.exp(-a[1]/this.a)))/f]};
function N(a){a=a||{};H.call(this,a);var c=a.D,b=a.H*f,d=a.I*f,e=a.F*f;this.a=a.s/a.u;this.e=a.n*f;this.g=a.B;this.h=a.C;a=1/c;c=2*a-a*a;this.d=Math.sqrt(c);a=this.i(b,c);c=this.i(d,c);b=O(this,b,this.d);d=O(this,d,this.d);e=O(this,e,this.d);this.b=(a*a-c*c)/(d-b);this.w=a*a+this.b*b;this.f=this.l(this.a,this.w,this.b,e)}N.prototype=new H;N.prototype.i=function(a,c){var b=Math.sin(a);return Math.cos(a)/Math.sqrt(1-c*b*b)};
function O(a,c,b){a=b*Math.sin(c);return(1-b*b)*(Math.sin(c)/(1-a*a)-1/(2*b)*Math.log((1-a)/(1+a)))}N.prototype.l=function(a,c,b,d){return a*Math.sqrt(c-b*d)/b};N.prototype.k=function(a,c,b){var d=c*Math.sin(b);return b+(1-d*d)*(1-d*d)/(2*Math.cos(b))*(a/(1-c*c)-Math.sin(b)/(1-d*d)+Math.log((1-d)/(1+d))/(2*c))};N.prototype.G=function(a,c,b){var d=0;b=b;for(var e=this.k(a,c,b);Math.abs(e-b)>1.0E-8&&d<10;){d++;b=e;e=this.k(a,c,b)}return e};
N.prototype.forward=function(a){var c=a[0]*f;a=this.l(this.a,this.w,this.b,O(this,a[1]*f,this.d));c=this.b*(c-this.e);return[this.g+a*Math.sin(c),this.h+this.f-a*Math.cos(c)]};N.prototype.inverse=function(a){var c=a[0]-this.g;a=a[1]-this.h;var b=Math.sqrt(c*c+(this.f-a)*(this.f-a)),d=this.b>0?1:-1;b=(this.w-b*b*this.b*this.b/(this.a*this.a))/this.b;return[(Math.atan(d*c/(d*this.f-d*a))/this.b+this.e)/f,this.G(b,this.d,Math.asin(b/2))/f]};N.prototype.m=function(){return Math.PI*2*this.a};
M.prototype.m=function(){return Math.PI*2*this.a};k=new I({wkid:4326});l=new I({wkid:4269});n=new M({wkid:102113,semi_major:6378137,central_meridian:0,unit:1});p={"4326":k,"4269":l,"102113":n,"102100":new M({wkid:102100,semi_major:6378137,central_meridian:0,unit:1})};
H.register=function(a,c){var b=p[""+a];if(b)return b;if(c instanceof H)b=p[""+a]=c;else{b=c||a;var d={wkt:a};if(a===parseInt(a,10))d={wkid:a};var e=r(b,'PROJECTION["','"]'),i=r(b,"SPHEROID[","]").split(",");if(e!==""){d.u=parseFloat(r(r(b,"PROJECTION",""),"UNIT[","]").split(",")[1]);d.s=parseFloat(i[1]);d.D=parseFloat(i[2]);d.F=parseFloat(r(b,'"Latitude_Of_Origin",',"]"));d.n=parseFloat(r(b,'"Central_Meridian",',"]"));d.B=parseFloat(r(b,'"False_Easting",',"]"));d.C=parseFloat(r(b,'"False_Northing",',
"]"))}switch(e){case "":b=new H(d);break;case "Lambert_Conformal_Conic":d.H=parseFloat(r(b,'"Standard_Parallel_1",',"]"));d.I=parseFloat(r(b,'"Standard_Parallel_2",',"]"));b=new J(d);break;case "Transverse_Mercator":d.T=parseFloat(r(b,'"Scale_Factor",',"]"));b=new L(d);break;case "Albers":d.H=parseFloat(r(b,'"Standard_Parallel_1",',"]"));d.I=parseFloat(r(b,'"Standard_Parallel_2",',"]"));b=new N(d);break;default:throw new Error(e+"  not supported");}if(b)p[""+a]=b}return b};
function P(a){this.S=a?a.q:null;this.t=a?p[a.U.v||a.U.J]:n;if(!this.t)throw new Error("unsupported Spatial Reference");this.Q=a?a.q[0].P:156543.033928;this.minZoom=Math.floor(Math.log(this.t.m()/this.Q/256)/Math.LN2+0.5);this.maxZoom=a?this.minZoom+this.S.length-1:20;if(j.Size)this.Y=a?new j.Size(a.cols,a.rows):new j.Size(256,256);this.r=Math.pow(2,this.minZoom)*this.Q;this.M=a?a.origin.x:-2.0037508342787E7;this.N=a?a.origin.y:2.0037508342787E7;if(a)for(var c,b=0;b<a.q.length-1;b++){c=a.q[b].P/a.q[b+
1].P;if(c>2.001||c<1.999)throw new Error("This type of map cache is not supported in V3. \nScale ratio between zoom levels must be 2");}}P.prototype.fromLatLngToPoint=function(a,c){if(!a||isNaN(a.lat())||isNaN(a.lng()))return null;var b=this.t.forward([a.lng(),a.lat()]),d=c||new j.Point(0,0);d.x=(b[0]-this.M)/this.r;d.y=(this.N-b[1])/this.r;return d};P.prototype.fromPointToLatLng=function(a){if(a===null)return null;a=this.t.inverse([a.x*this.r+this.M,this.N-a.y*this.r]);return new j.LatLng(a[1],a[0])};
new P;j.OverlayView&&new j.OverlayView;})()
