function G(n){return function(){return this[n]}}
(function(){function n(a,b,c){var d=b===""?0:a.indexOf(b);return a.substring(d+b.length,c===""?a.length:a.indexOf(c,d+b.length))}function H(a){return a&&typeof a==="string"}function r(a){return a&&a.splice}function m(a,b,c){if(a&&b){var d;for(d in a)if(c||!(d in b))b[d]=a[d]}return b}function N(){i.event.trigger.apply(this,arguments)}function w(a,b){a&&b&&b.error&&a(b.error)}function aa(a,b){var c="";if(a)c+=a.getTime()-a.getTimezoneOffset()*6E4;if(b)c+=", "+(b.getTime()-b.getTimezoneOffset()*6E4);
return c}function I(a,b){b=Math.min(Math.max(b,0),1);if(a){var c=a.style;if(typeof c.opacity!=="undefined")c.opacity=b;if(typeof c.filters!=="undefined")c.filters.alpha.opacity=Math.floor(100*b);if(typeof c.filter!=="undefined")c.filter="alpha(opacity:"+Math.floor(b*100)+")"}}function V(a){var b="";for(var c in a)if(a.hasOwnProperty(c)){if(b.length>0)b+=";";b+=c+":"+a[c]}return b}function ja(){if(typeof XMLHttpRequest==="undefined"){try{return new ActiveXObject("Msxml2.XMLHTTP.6.0")}catch(a){}try{return new ActiveXObject("Msxml2.XMLHTTP.3.0")}catch(b){}try{return new ActiveXObject("Msxml2.XMLHTTP")}catch(c){}throw new Error("This browser does not support XMLHttpRequest.");
}else return new XMLHttpRequest}function S(a){var b=a;if(r(a)&&a.length>0)b=a[0];if(b instanceof i.LatLng||b instanceof i.Marker)return r(a)&&a.length>1?s.MULTIPOINT:s.POINT;else if(b instanceof i.Polyline)return s.POLYLINE;else if(b instanceof i.Polygon)return s.POLYGON;else if(b instanceof i.LatLngBounds)return s.ENVELOPE;else if(b.x!==undefined&&b.y!==undefined)return s.POINT;else if(b.points)return s.MULTIPOINT;else if(b.paths)return s.POLYLINE;else if(b.rings)return s.POLYGON;return null}function W(a){var b=
a;if(r(a)&&a.length>0)b=a[0];if(r(b)&&b.length>0)b=b[0];if(b instanceof i.LatLng||b instanceof i.Marker||b instanceof i.Polyline||b instanceof i.Polygon||b instanceof i.LatLngBounds)return true;return false}function O(a){if(!a)return null;return typeof a==="number"?a:a.wkid?a.wkid:a.toJSON()}function ba(a,b){for(var c=[],d,e=0,f=a.getLength();e<f;e++){d=a.getAt(e);c.push("["+d.lng()+","+d.lat()+"]")}b&&c.length>0&&c.push("["+a.getAt(0).lng()+","+a.getAt(0).lat()+"]");return c.join(",")}function J(a){var b,
c,d,e="{";switch(S(a)){case s.POINT:b=r(a)?a[0]:a;if(b instanceof i.Marker)b=b.getPosition();e+="x:"+b.lng()+",y:"+b.lat();break;case s.MULTIPOINT:d=[];for(c=0;c<a.length;c++){b=a[c]instanceof i.Marker?a[c].getPosition():a[c];d.push("["+b.lng()+","+b.lat()+"]")}e+="points: ["+d.join(",")+"]";break;case s.POLYLINE:d=[];a=r(a)?a:[a];for(c=0;c<a.length;c++)d.push("["+ba(a[c].getPath())+"]");e+="paths:["+d.join(",")+"]";break;case s.POLYGON:d=[];b=r(a)?a[0]:a;a=b.getPaths();for(c=0;c<a.getLength();c++)d.push("["+
ba(a.getAt(c),true)+"]");e+="rings:["+d.join(",")+"]";break;case s.ENVELOPE:b=r(a)?a[0]:a;e+="xmin:"+b.getSouthWest().lng()+",ymin:"+b.getSouthWest().lat()+",xmax:"+b.getNorthEast().lng()+",ymax:"+b.getNorthEast().lat();break}e+=", spatialReference:{wkid:4326}";e+="}";return e}function ka(a){function b(e){for(var f=[],g=0,h=e.length;g<h;g++)f.push("["+e[g][0]+","+e[g][1]+"]");return"["+f.join(",")+"]"}function c(e){for(var f=[],g=0,h=e.length;g<h;g++)f.push(b(e[g]));return"["+f.join(",")+"]"}var d=
"{";if(a.x)d+="x:"+a.x+",y:"+a.y;else if(a.xmin)d+="xmin:"+a.xmin+",ymin:"+a.ymin+",xmax:"+a.xmax+",ymax:"+a.ymax;else if(a.points)d+="points:"+b(a.points);else if(a.paths)d+="paths:"+c(a.paths);else if(a.rings)d+="rings:"+c(a.rings);d+="}";return d}function ca(a){var b=z[a.spatialReference.wkid||a.spatialReference.wkt];b=b||K;var c=b.inverse([a.xmin,a.ymin]);a=b.inverse([a.xmax,a.ymax]);return new i.LatLngBounds(new i.LatLng(c[1],c[0]),new i.LatLng(a[1],a[0]))}function L(a,b){var c=null,d,e,f,g,
h,j,A,t;b=b||{};if(a){c=[];if(a.x){d=new i.Marker(m(b.markerOptions||b,{position:new i.LatLng(a.y,a.x)}));c.push(d)}else{h=a.points||a.paths||a.rings;if(!h)return c;var da=[];e=0;for(f=h.length;e<f;e++){j=h[e];if(a.points){d=new i.Marker(m(b.markerOptions||b,{position:new i.LatLng(j[1],j[0])}));c.push(d)}else{t=[];d=0;for(g=j.length;d<g;d++){A=j[d];t.push(new i.LatLng(A[1],A[0]))}if(a.paths){d=new i.Polyline(m(b.polylineOptions||b,{path:t}));c.push(d)}else a.rings&&da.push(t)}}if(a.rings){d=new i.Polygon(m(b.polygonOptions||
b,{paths:da}));c.push(d)}}}return c}function ea(a,b){if(a){var c,d,e;c=0;for(d=a.length;c<d;c++){e=a[c];if(e.geometry)e.geometry=L(e.geometry,b)}}}function X(a){var b;if(typeof a==="object")if(r(a)){b=[];for(var c=0,d=a.length;c<d;c++)b.push(X(a[c]));return"["+b.join(",")+"]"}else if(W(a))return J(a);else if(a.toJSON)return a.toJSON();else{b="";for(c in a)if(a.hasOwnProperty(c)){if(b.length>0)b+=", ";b+=c+":"+X(a[c])}return"{"+b+"}"}return a.toString()}function fa(a){var b,c,d,e=[];b=0;for(c=a.length;b<
c;b++){d=a[b];if(d instanceof i.Marker)d=d.getPosition();e.push({geometry:{x:d.lng(),y:d.lat(),spatialReference:{wkid:4326}}})}return{type:'"features"',features:e,doNotLocateOnRestrictedElements:false}}function ga(a){var b={};if(!a)return null;var c=[],d,e;if(a.geometries&&a.geometries.length>0){d=a.geometries[0];e=W(d);for(var f=0,g=a.geometries.length;f<g;f++)e?c.push(J(a.geometries[f])):c.push(ka(a.geometries[f]))}a.geometryType||(a.geometryType=S(d));if(e)b.inSR=K.wkid;else if(a.inSpatialReference)b.inSR=
O(a.inSpatialReference);if(a.outSpatialReference)b.outSR=O(a.outSpatialReference);b.geometries='{geometryType:"'+a.geometryType+'", geometries:['+c.join(",")+"]}";return b}function o(a,b,c,d){var e="ags_jsonp"+la++ +"_"+Math.floor(Math.random()*1E6),f=null,g="";if(b){b.f=b.f||p.P;for(var h in b)if(b.hasOwnProperty(h)&&b[h]!==null&&b[h]!==undefined){var j=X(b[h]);g+=h+"="+(escape?escape(j):encodeURIComponent(j))+"&"}}g+=c+"=ags_jsonp."+e;var A=document.getElementsByTagName("head")[0];if(!A)throw new Error("document must have header tag");
x.ags_jsonp[e]=function(){delete x.ags_jsonp[e];f&&A.removeChild(f);f=null;d.apply(null,arguments);N(C,"jsonpend",e)};if((g+a).length<2E3&&!P.alwaysUseProxy){f=document.createElement("script");f.src=a+(a.indexOf("?")===-1?"?":"&")+g;f.id=e;A.appendChild(f)}else{b=window.location;b=b.protocol+"//"+b.hostname+(!b.port||b.port===80?"":":"+b.port+"/");c=true;if(a.toLowerCase().indexOf(b.toLowerCase())!==-1)c=false;if(P.alwaysUseProxy)c=true;if(c&&!P.proxyUrl)throw new Error("No proxyUrl property in Config is defined");
var t=ja();t.onreadystatechange=function(){if(t.readyState===4)if(t.status===200)eval(t.responseText);else throw new Error("Error code "+t.status);};t.open("POST",c?P.proxyUrl+"?"+a:a,true);t.setRequestHeader("Content-Type","application/x-www-form-urlencoded");t.send(g)}N(C,"jsonpstart",e);return e}function l(a){a=a||{};this.wkid=a.wkid;this.wkt=a.wkt}function T(a){a=a||{};l.call(this,a)}function u(a){a=a||{};l.call(this,a);var b=a.inverse_flattening,c=a.standard_parallel_1*k,d=a.standard_parallel_2*
k,e=a.latitude_of_origin*k;this.a=a.semi_major/a.unit;this.i=a.central_meridian*k;this.k=a.false_easting;this.l=a.false_northing;a=1/b;b=2*a-a*a;this.h=Math.sqrt(b);a=this.m(c,b);b=this.m(d,b);e=this.v(e,this.h);c=this.v(c,this.h);d=this.v(d,this.h);this.b=Math.log(a/b)/Math.log(c/d);this.I=a/(this.b*Math.pow(c,this.b));this.C=this.M(this.a,this.I,e,this.b)}function D(a){a=a||{};l.call(this,a);this.a=a.semi_major/a.unit;var b=a.inverse_flattening;this.A=a.scale_factor;var c=a.latitude_of_origin*k;
this.i=a.central_meridian*k;this.k=a.false_easting;this.l=a.false_northing;a=1/b;this.d=2*a-a*a;this.z=this.d*this.d;this.J=this.z*this.d;this.o=this.d/(1-this.d);this.L=this.m(c,this.a,this.d,this.z,this.J)}function E(a){a=a||{};l.call(this,a);this.a=(a.semi_major||6378137)/(a.unit||1);this.i=(a.central_meridian||0)*k}function v(a){a=a||{};l.call(this,a);var b=a.inverse_flattening,c=a.standard_parallel_1*k,d=a.standard_parallel_2*k,e=a.latitude_of_origin*k;this.a=a.semi_major/a.unit;this.i=a.central_meridian*
k;this.k=a.false_easting;this.l=a.false_northing;a=1/b;b=2*a-a*a;this.h=Math.sqrt(b);a=this.m(c,b);b=this.m(d,b);c=this.u(c,this.h);d=this.u(d,this.h);e=this.u(e,this.h);this.b=(a*a-b*b)/(d-c);this.H=a*a+this.b*c;this.D=this.N(this.a,this.H,this.b,e)}function F(a){this.url=a;this.definition=null}function q(a){this.url=a;this.loaded=false;var b=a.split("/");this.name=b[b.length-2].replace(/_/g," ");var c=this;o(a,{},p.g,function(d){c.q(d)})}function Q(a){this.url=a;this.loaded=false;var b=this;o(a,
{},p.g,function(c){b.q(c)})}function Y(a){this.url=a}function ha(a){this.url=a;this.loaded=false;var b=this;o(a,{},p.g,function(c){m(c,b);b.loaded=true;i.event.trigger(b,p.load)})}function ia(a){this.url=a}function R(a){if(!a)throw new Error("map service is not tiled");this.Q=a.lods;this.G=z[a.spatialReference.wkid||a.spatialReference.wkt];if(!this.G)throw new Error("unsupported Spatial Reference");this.U=this.Q[0].resolution;this.minZoom=Math.floor(Math.log(this.G.s()/this.U/256)/Math.LN2+0.5);this.maxZoom=
this.minZoom+this.Q.length-1;this.tileSize=new i.Size(a.cols,a.rows);this.F=Math.pow(2,this.minZoom)*this.U;this.S=a.origin.x;this.T=a.origin.y;for(var b,c=0;c<a.lods.length-1;c++){b=a.lods[c].resolution/a.lods[c+1].resolution;if(b>2.001||b<1.999)throw new Error("This type of map cache is not supported in V3. \nScale ratio between zoom levels must be 2");}}function y(a,b){b=b||{};if(b.opacity){this.c=b.opacity;delete b.opacity}m(b,this);this.e=a instanceof q?a:new q(a);if(b.hosts){var c=n(this.e.url,
"","://");this.V=c+"://"+b.hosts+n(this.e.url,c+"://"+n(this.e.url,"://","/"),"");this.R=parseInt(n(b.hosts,"[","]"),10)}this.name=this.name||this.e.name;this.maxZoom=this.maxZoom||19;this.minZoom=this.minZoom||0;if(this.e.loaded)this.q(b);else{var d=this;i.event.addListenerOnce(this.e,p.load,function(){d.q(b)})}this.j={}}function M(a,b){b=b||{};var c;if(b.opacity){this.c=b.opacity;delete b.opacity}m(b,this);var d=a;if(H(a))d=[new y(a)];else if(a instanceof q)d=[new y(a)];else if(a instanceof y)d=
[a];else if(a.length>0&&H(a[0])){d=[];for(c=0;c<a.length;c++)d[c]=new y(a[c])}this.t=d;this.j={};if(b.maxZoom!==undefined)this.maxZoom=b.maxZoom;else{var e=0;for(c=0;c<d.length;c++)e=Math.max(e,d[c].maxZoom);this.maxZoom=e}if(d[0].p){this.tileSize=d[0].p.tileSize;this.projection=d[0].p}else this.tileSize=new i.Size(256,256);this.name||(this.name=d[0].name)}function B(a,b){b=b||{};this.e=a instanceof q?a:new q(a);this.c=b.opacity||1;this.X=b.exportOptions||{};this.B=this.w=false;this.n=null;b.map&&
this.setMap(b.map)}var p={P:"json",g:"callback",load:"load"},k=Math.PI/180,la=0,x=window;x.ags_jsonp=x.ags_jsonp||{};x.gmaps=x.gmaps||{};var i=x.google&&x.google.maps?x.google.maps:{},K,Z,U,$,P={proxyUrl:null,alwaysUseProxy:false},z={},s={POINT:"esriGeometryPoint",MULTIPOINT:"esriGeometryMultipoint",POLYLINE:"esriGeometryPolyline",POLYGON:"esriGeometryPolygon",ENVELOPE:"esriGeometryEnvelope"},C={};C.getJSON=function(a,b,c,d){o(a,b,c,d)};C.addToMap=function(a,b){if(r(b))for(var c,d=0,e=b.length;d<
e;d++){c=b[d];if(r(c))C.addToMap(a,c);else W(c)&&c.setMap(a)}};C.removeFromMap=function(a,b){C.addToMap(null,a);if(b)a.length=0};l.prototype.forward=function(a){return a};l.prototype.inverse=function(a){return a};l.prototype.s=function(){return 360};l.prototype.toJSON=function(){return"{"+(this.wkid?" wkid:"+this.wkid:"wkt: '"+this.wkt+"'")+"}"};T.prototype=new l;u.prototype=new l;u.prototype.m=function(a,b){var c=Math.sin(a);return Math.cos(a)/Math.sqrt(1-b*c*c)};u.prototype.v=function(a,b){var c=
b*Math.sin(a);return Math.tan(Math.PI/4-a/2)/Math.pow((1-c)/(1+c),b/2)};u.prototype.M=function(a,b,c,d){return a*b*Math.pow(c,d)};u.prototype.r=function(a,b,c){c=b*Math.sin(c);return Math.PI/2-2*Math.atan(a*Math.pow((1-c)/(1+c),b/2))};u.prototype.K=function(a,b,c){var d=0;c=c;for(var e=this.r(a,b,c);Math.abs(e-c)>1.0E-9&&d<10;){d++;c=e;e=this.r(a,b,c)}return e};u.prototype.forward=function(a){var b=a[0]*k;a=this.M(this.a,this.I,this.v(a[1]*k,this.h),this.b);b=this.b*(b-this.i);return[this.k+a*Math.sin(b),
this.l+this.C-a*Math.cos(b)]};u.prototype.inverse=function(a){var b=a[0]-this.k;a=a[1]-this.l;return[(Math.atan(b/(this.C-a))/this.b+this.i)/k,this.K(Math.pow((this.b>0?1:-1)*Math.sqrt(b*b+(this.C-a)*(this.C-a))/(this.a*this.I),1/this.b),this.h,0)/k]};u.prototype.s=function(){return Math.PI*2*this.a};D.prototype=new l;D.prototype.m=function(a,b,c,d,e){return b*((1-c/4-3*d/64-5*e/256)*a-(3*c/8+3*d/32+45*e/1024)*Math.sin(2*a)+(15*d/256+45*e/1024)*Math.sin(4*a)-35*e/3072*Math.sin(6*a))};D.prototype.forward=
function(a){var b=a[1]*k,c=a[0]*k;a=this.a/Math.sqrt(1-this.d*Math.pow(Math.sin(b),2));var d=Math.pow(Math.tan(b),2),e=this.o*Math.pow(Math.cos(b),2);c=(c-this.i)*Math.cos(b);var f=this.m(b,this.a,this.d,this.z,this.J);return[this.k+this.A*a*(c+(1-d+e)*Math.pow(c,3)/6+(5-18*d+d*d+72*e-58*this.o)*Math.pow(c,5)/120),this.l+this.A*(f-this.L)+a*Math.tan(b)*(c*c/2+(5-d+9*e+4*e*e)*Math.pow(c,4)/120+(61-58*d+d*d+600*e-330*this.o)*Math.pow(c,6)/720)]};D.prototype.inverse=function(a){var b=a[0],c=a[1];a=(1-
Math.sqrt(1-this.d))/(1+Math.sqrt(1-this.d));c=(this.L+(c-this.l)/this.A)/(this.a*(1-this.d/4-3*this.z/64-5*this.J/256));a=c+(3*a/2-27*Math.pow(a,3)/32)*Math.sin(2*c)+(21*a*a/16-55*Math.pow(a,4)/32)*Math.sin(4*c)+151*Math.pow(a,3)/6*Math.sin(6*c)+1097*Math.pow(a,4)/512*Math.sin(8*c);c=this.o*Math.pow(Math.cos(a),2);var d=Math.pow(Math.tan(a),2),e=this.a/Math.sqrt(1-this.d*Math.pow(Math.sin(a),2)),f=this.a*(1-this.d)/Math.pow(1-this.d*Math.pow(Math.sin(a),2),1.5);b=(b-this.k)/(e*this.A);e=a-e*Math.tan(a)/
f*(b*b/2-(5+3*d+10*c-4*c*c-9*this.o)*Math.pow(b,4)/24+(61+90*d+28*c+45*d*d-252*this.o-3*c*c)*Math.pow(b,6)/720);return[(this.i+(b-(1+2*d+c)*Math.pow(b,3)/6+(5-2*c+28*d-3*c*c+8*this.o+24*d*d)*Math.pow(b,5)/120)/Math.cos(a))/k,e/k]};D.prototype.s=function(){return Math.PI*2*this.a};E.prototype=new l;E.prototype.forward=function(a){var b=a[1]*k;return[this.a*(a[0]*k-this.i),this.a/2*Math.log((1+Math.sin(b))/(1-Math.sin(b)))]};E.prototype.inverse=function(a){return[(a[0]/this.a+this.i)/k,(Math.PI/2-2*
Math.atan(Math.exp(-a[1]/this.a)))/k]};v.prototype=new l;v.prototype.m=function(a,b){var c=Math.sin(a);return Math.cos(a)/Math.sqrt(1-b*c*c)};v.prototype.u=function(a,b){var c=b*Math.sin(a);return(1-b*b)*(Math.sin(a)/(1-c*c)-1/(2*b)*Math.log((1-c)/(1+c)))};v.prototype.N=function(a,b,c,d){return a*Math.sqrt(b-c*d)/c};v.prototype.r=function(a,b,c){var d=b*Math.sin(c);return c+(1-d*d)*(1-d*d)/(2*Math.cos(c))*(a/(1-b*b)-Math.sin(c)/(1-d*d)+Math.log((1-d)/(1+d))/(2*b))};v.prototype.K=function(a,b,c){var d=
0;c=c;for(var e=this.r(a,b,c);Math.abs(e-c)>1.0E-8&&d<10;){d++;c=e;e=this.r(a,b,c)}return e};v.prototype.forward=function(a){var b=a[0]*k;a=this.N(this.a,this.H,this.b,this.u(a[1]*k,this.h));b=this.b*(b-this.i);return[this.k+a*Math.sin(b),this.l+this.D-a*Math.cos(b)]};v.prototype.inverse=function(a){var b=a[0]-this.k;a=a[1]-this.l;var c=Math.sqrt(b*b+(this.D-a)*(this.D-a)),d=this.b>0?1:-1;c=(this.H-c*c*this.b*this.b/(this.a*this.a))/this.b;return[(Math.atan(d*b/(d*this.D-d*a))/this.b+this.i)/k,this.K(c,
this.h,Math.asin(c/2))/k]};v.prototype.s=function(){return Math.PI*2*this.a};E.prototype.s=function(){return Math.PI*2*this.a};K=new T({wkid:4326});Z=new T({wkid:4269});U=new E({wkid:102113,semi_major:6378137,central_meridian:0,unit:1});$=new E({wkid:102100,semi_major:6378137,central_meridian:0,unit:1});z={"4326":K,"4269":Z,"102113":U,"102100":$};l.WGS84=K;l.NAD83=Z;l.WEB_MERCATOR=U;l.WEB_MERCATOR_AUX=$;l.register=function(a,b){var c=z[""+a];if(c)return c;if(b instanceof l)c=z[""+a]=b;else{c=b||a;
var d={wkt:a};if(a===parseInt(a,10))d={wkid:a};var e=n(c,'PROJECTION["','"]'),f=n(c,"SPHEROID[","]").split(",");if(e!==""){d.unit=parseFloat(n(n(c,"PROJECTION",""),"UNIT[","]").split(",")[1]);d.semi_major=parseFloat(f[1]);d.inverse_flattening=parseFloat(f[2]);d.latitude_of_origin=parseFloat(n(c,'"Latitude_Of_Origin",',"]"));d.central_meridian=parseFloat(n(c,'"Central_Meridian",',"]"));d.false_easting=parseFloat(n(c,'"False_Easting",',"]"));d.false_northing=parseFloat(n(c,'"False_Northing",',"]"))}switch(e){case "":c=
new l(d);break;case "Lambert_Conformal_Conic":d.standard_parallel_1=parseFloat(n(c,'"Standard_Parallel_1",',"]"));d.standard_parallel_2=parseFloat(n(c,'"Standard_Parallel_2",',"]"));c=new u(d);break;case "Transverse_Mercator":d.scale_factor=parseFloat(n(c,'"Scale_Factor",',"]"));c=new D(d);break;case "Albers":d.standard_parallel_1=parseFloat(n(c,'"Standard_Parallel_1",',"]"));d.standard_parallel_2=parseFloat(n(c,'"Standard_Parallel_2",',"]"));c=new v(d);break;default:throw new Error(e+"  not supported");
}if(c)z[""+a]=c}return c};F.prototype.loadInfo=function(a){var b=this;this.loaded||o(this.url,{},"callback",function(c){m(c,b);b.loaded=true;a&&a()})};F.prototype.isInScale=function(a){if(this.maxScale&&this.maxScale>a)return false;if(this.minScale&&this.minScale<a)return false;return true};F.prototype.query=function(a,b,c){if(a){var d=m(a,{});if(a.geometry&&!H(a.geometry)){d.geometry=J(a.geometry);d.geometryType=S(a.geometry);d.inSR=4326}if(a.spatialRelationship){d.spatialRel=a.spatialRelationship;
delete d.spatialRelationship}if(a.outFields&&!r(a.outFields))d.outFields=a.outFields.join(",");if(a.objectIds)d.objectIds=a.objectIds.join(",");if(a.time)d.time=aa(a.time,a.endTime);d.outSR=4326;d.returnGeometry=a.returnGeometry===false?false:true;d.returnIdsOnly=a.returnIdsOnly===true?true:false;delete d.overlayOptions;o(this.url+"/query",d,"callback",function(e){ea(e.features,a.overlayOptions);b(e,e.error);w(c,e)})}};F.prototype.queryRelatedRecords=function(a,b,c){if(a){a=m(a,{});a.f=a.f||"json";
if(a.outFields&&!H(a.outFields))a.outFields=a.outFields.join(",");a.returnGeometry=a.returnGeometry===false?false:true;o(this.url+"/query",a,p.g,function(d){w(c,d);b(d)})}};q.prototype.q=function(a){var b=this;m(a,this);this.spatialReference=a.spatialReference.wkt?z.$(a.spatialReference.wkt,a.spatialReference.wkt):z[a.spatialReference.wkid];a.tables!==undefined?o(this.url+"/layers",{},p.g,function(c){b.O(c)}):this.O(a)};q.prototype.O=function(a){var b=[],c=[],d,e,f,g;e=0;for(f=a.layers.length;e<f;e++){g=
a.layers[e];d=new F(this.url+"/"+g.id);m(g,d);d.visible=d.defaultVisibility;b.push(d)}if(a.tables){e=0;for(f=a.tables.length;e<f;e++){g=a.tables[e];d=new F(this.url+"/"+g.id);m(g,d);c.push(d)}}e=0;for(f=b.length;e<f;e++){d=b[e];if(d.subLayerIds){d.subLayers=[];g=0;for(var h=d.subLayerIds.length;g<h;g++){var j=this.getLayer(d.subLayerIds[g]);d.subLayers.push(j);j.parentLayer=d}}}this.layers=b;if(a.tables)this.tables=c;this.loaded=true;N(this,"load")};q.prototype.getLayer=function(a){var b=this.layers;
if(b)for(var c=0,d=b.length;c<d;c++){if(a===b[c].id)return b[c];if(H(a)&&b[c].name.toLowerCase()===a.toLowerCase())return b[c]}return null};q.prototype.Y=function(){var a={};if(this.layers)for(var b=0,c=this.layers.length;b<c;b++){var d=this.layers[b];if(d.definition)a[String(d.id)]=d.definition}return a};q.prototype.Z=function(){var a=[];if(this.layers){var b,c,d;c=0;for(d=this.layers.length;c<d;c++){b=this.layers[c];if(b.subLayers)for(var e=0,f=b.subLayers.length;e<f;e++)if(b.subLayers[e].visible===
false){b.visible=false;break}}c=0;for(d=this.layers.length;c<d;c++){b=this.layers[c];b.visible===true&&a.push(b.id)}}return a};q.prototype.getInitialBounds=function(){if(this.initialExtent)return ca(this.initialExtent);return null};q.prototype.exportMap=function(a,b){if(a&&a.bounds){var c={},d=a.bounds;c.bbox=""+d.getSouthWest().lng()+","+d.getSouthWest().lat()+","+d.getNorthEast().lng()+","+d.getNorthEast().lat();c.size=""+a.width+","+a.height;c.dpi=a.dpi;if(a.imageSR)c.imageSR=a.imageSR.wkid?a.imageSR.wkid:
"{wkt:"+a.imageSR.wkt+"}";c.bboxSR="4326";c.format=a.format;d=a.layerDefinitions;if(d===undefined)d=this.Y();c.layerDefs=V(d);d=a.layerIds;var e=a.layerOption||"show";if(d===undefined)d=this.Z();if(d.length>0){c.layers=e+":"+d.join(",");c.transparent=a.transparent===false?false:true;if(a.time)c.time=aa(a.time,a.endTime);c.layerTimeOptions=a.layerTimeOptions;o(this.url+"/export",c,"callback",function(f){f.bounds=ca(f.extent);delete f.extent;b(f)})}else b({href:null})}};q.prototype.identify=function(a,
b,c){if(a){var d={};d.geometry=J(a.geometry);d.geometryType=S(a.geometry);d.mapExtent=J(a.bounds);d.tolerance=a.tolerance||2;d.sr=4326;d.imageDisplay=""+a.width+","+a.height+","+(a.dpi||96);d.layers=a.layerOption||"all";if(a.layerIds)d.layers+=":"+a.layerIds.join(",");if(a.layerDefs)d.layerDefs=V(a.layerDefs);d.maxAllowableOffset=a.maxAllowableOffset;d.returnGeometry=a.returnGeometry===false?false:true;o(this.url+"/identify",d,"callback",function(e){var f,g,h;if(e.results)for(f=0;f<e.results.length;f++){g=
e.results[f];h=L(g.geometry,a.overlayOptions);g.feature={geometry:h,attributes:g.attributes};delete g.attributes}b(e);w(c,e)})}};q.prototype.find=function(a,b,c){if(a){var d=m(a,{});if(a.layerIds){d.layers=a.layerIds.join(",");delete d.layerIds}if(a.searchFields)d.searchFields=a.searchFields.join(",");d.contains=a.contains===false?false:true;if(a.layerDefinitions){d.layerDefs=V(a.layerDefinitions);delete d.layerDefinitions}d.sr=4326;d.returnGeometry=a.returnGeometry===false?false:true;o(this.url+
"/find",d,p.g,function(e){var f,g,h;if(e.results)for(f=0;f<e.results.length;f++){g=e.results[f];h=L(g.geometry,a.overlayOptions);g.feature={geometry:h,attributes:g.attributes};delete g.attributes}b(e);w(c,e)})}};q.prototype.queryLayer=function(a,b,c,d){(a=this.getLayer(a))&&a.query(b,c,d)};Q.prototype.q=function(a){m(a,this);if(a.spatialReference)this.spatialReference=z[a.spatialReference.wkid||a.spatialReference.wkt]||K;this.loaded=true;N(this,"load")};Q.prototype.findAddressCandidates=function(a,
b,c){a=m(a,{});if(a.inputs){m(a.inputs,a);delete a.inputs}if(r(a.outFields))a.outFields=a.outFields.join(",");a.outSR=4326;var d=this;o(this.url+"/findAddressCandidates",a,p.g,function(e){if(e.candidates)for(var f,g,h=0;h<e.candidates.length;h++){f=e.candidates[h];g=f.location;if(!isNaN(g.x)&&!isNaN(g.y)){g=[g.x,g.y];if(d.spatialReference)g=d.spatialReference.inverse(g);f.location=new i.LatLng(g[1],g[0])}}b(e);w(c,e)})};Q.prototype.geocode=function(a,b){this.findAddressCandidates(a,b)};Q.prototype.reverseGeocode=
function(a,b,c){H(a.location)||(a.location=J(a.location));a.outSR=4326;var d=this;o(this.url+"/reverseGeocode",a,p.g,function(e){if(e.location){var f=e.location;if(!isNaN(f.x)&&!isNaN(f.y)){f=[f.x,f.y];if(d.spatialReference)f=d.spatialReference.inverse(f);e.location=new i.LatLng(f[1],f[0])}}b(e);w(c,e)})};Y.prototype.project=function(a,b,c){var d=ga(a);o(this.url+"/project",d,"callback",function(e){var f=[];if(a.outSpatialReference===4326||a.outSpatialReference.wkid===4326){for(var g=0,h=e.geometries.length;g<
h;g++)f.push(L(e.geometries[g]));e.geometries=f}b(e);w(c,e)})};Y.prototype.buffer=function(a,b,c){var d=ga(a);if(a.bufferSpatialReference)d.bufferSR=O(a.bufferSpatialReference);d.outSR=4326;d.distances=a.distances.join(",");if(a.unit)d.unit=a.unit;o(this.url+"/buffer",d,"callback",function(e){var f=[];if(e.geometries)for(var g=0,h=e.geometries.length;g<h;g++)f.push(L(e.geometries[g],a.overlayOptions));e.geometries=f;b(e);w(c,e)})};ha.prototype.execute=function(a,b,c){var d={};a.parameters&&m(a.parameters,
d);d["env:outSR"]=a.outSpatialReference?O(a.outSpatialReference):4326;if(a.processSpatialReference)d["env:processSR"]=O(a.processSpatialReference);o(this.url+"/execute",d,p.g,function(e){if(e.results)for(var f,g,h=0;h<e.results.length;h++){f=e.results[h];if(f.dataType==="GPFeatureRecordSetLayer")for(var j=0,A=f.value.features.length;j<A;j++){g=f.value.features[j];if(g.geometry)g.geometry=L(g.geometry,a.overlayOptions)}}b(e);w(c,e)})};ia.prototype.solve=function(a,b,c){if(a){var d=m(a,{});if(r(a.stops))d.stops=
fa(a.stops);if(r(a.barriers))if(a.barriers.length>0)d.barriers=fa(a.barriers);else delete d.barriers;d.returnRoutes=a.returnRoutes===false?false:true;d.returnDirections=a.returnDirections===true?true:false;d.returnBarriers=a.returnBarriers===true?true:false;d.returnStops=a.returnStops===true?true:false;o(this.url+"/solve",d,"callback",function(e){e.routes&&ea(e.routes.features,a.overlayOptions);b(e);w(c,e)})}};R.prototype.fromLatLngToPoint=function(a,b){if(!a||isNaN(a.lat())||isNaN(a.lng()))return null;
var c=this.G.forward([a.lng(),a.lat()]),d=b||new i.Point(0,0);d.x=(c[0]-this.S)/this.F;d.y=(this.T-c[1])/this.F;return d};R.prototype.fromPointToLatLng=function(a){if(a===null)return null;a=this.G.inverse([a.x*this.F+this.S,this.T-a.y*this.F]);return new i.LatLng(a[1],a[0])};y.prototype.q=function(a){this.p=new R(this.e.tileInfo);this.minZoom=a.minZoom||this.p.minZoom;this.maxZoom=a.maxZoom||this.p.maxZoom};y.prototype.getTileUrl=function(a,b){var c=b-(this.p?this.p.minZoom:this.minZoom),d="";if(!isNaN(a.x)&&
!isNaN(a.y)&&c>=0&&a.x>=0&&a.y>=0){d=this.e.url;if(this.V)d=this.V.replace("["+this.R+"]",""+(a.y+a.x)%this.R);d=d+"/tile/"+c+"/"+a.y+"/"+a.x}return d};y.prototype.setOpacity=function(a){this.c=a;var b=this.j;for(var c in b)b.hasOwnProperty(c)&&I(b[c],a)};y.prototype.getOpacity=G("c");y.prototype.getMapService=G("e");M.prototype.getTile=function(a,b,c){for(var d=c.createElement("div"),e="_"+a.x+"_"+a.y+"_"+b,f=0;f<this.t.length;f++){var g=this.t[f];if(b<=g.maxZoom&&b>=g.minZoom){var h=g.getTileUrl(a,
b);if(h){var j=c.createElement(document.all?"img":"div");j.style.border="0px none";j.style.margin="0px";j.style.padding="0px";j.style.overflow="hidden";j.style.position="absolute";j.style.top="0px";j.style.left="0px";j.style.width=""+this.tileSize.width+"px";j.style.height=""+this.tileSize.height+"px";if(document.all)j.src=h;else j.style.backgroundImage="url("+h+")";d.appendChild(j);g.j[e]=j;if(g.c!==undefined)I(j,g.c);else this.c!==undefined&&I(j,this.c)}}}this.j[e]=d;d.setAttribute("tid",e);return d};
M.prototype.releaseTile=function(a){if(a.getAttribute("tid")){a=a.getAttribute("tid");this.j[a]&&delete this.j[a];for(var b=0;b<this.t.length;b++){var c=this.t[b];c.j[a]&&delete c.j[a]}}};M.prototype.setOpacity=function(a){this.c=a;var b=this.j;for(var c in b)if(b.hasOwnProperty(c))for(var d=b[c].childNodes,e=0;e<d.length;e++)I(d[e],a)};M.prototype.getOpacity=G("c");M.prototype.getTileLayers=G("t");if(i.OverlayView)B.prototype=new i.OverlayView;B.prototype.onAdd=function(){var a=document.createElement("div");
a.style.position="absolute";a.style.border="none";a.style.position="absolute";this.n=a;this.getPanes().overlayLayer.appendChild(a);this.c&&I(a,this.c);var b=this;this.W=i.event.addListener(this.getMap(),"bounds_changed",function(){b.refresh()})};B.prototype.onRemove=function(){i.event.removeListener(this.W);this.n.parentNode.removeChild(this.n);this.n=null};B.prototype.draw=function(){if(!this.w||this.B===true)this.refresh()};B.prototype.getOpacity=G("c");B.prototype.setOpacity=function(a){this.c=
a=Math.min(Math.max(a,0),1);I(this.n,a)};B.prototype.getMapService=G("e");B.prototype.refresh=function(){if(this.w===true)this.B=true;else{var a=this.getMap(),b=a?a.getBounds():null;if(b){var c=this.X;c.bounds=b;b=U;var d=a.getDiv();c.width=d.offsetWidth;c.height=d.offsetHeight;if((a=a.getProjection())&&a instanceof R)b=a.spatialReference;c.imageSR=b;i.event.trigger(this,"drawstart");var e=this;this.w=true;this.n.style.backgroundImage="";this.e.exportMap(c,function(f){e.w=false;if(e.B===true){e.B=
false;e.refresh()}else{if(f.href){var g=e.getProjection(),h=f.bounds,j=g.fromLatLngToDivPixel(h.getSouthWest());g=g.fromLatLngToDivPixel(h.getNorthEast());h=e.n;h.style.left=j.x+"px";h.style.top=g.y+"px";h.style.width=g.x-j.x+"px";h.style.height=j.y-g.y+"px";e.n.style.backgroundImage="url("+f.href+")";e.setOpacity(e.c)}i.event.trigger(e,"drawend")}})}}};x.gmaps.ags={SpatialReference:l,Geographic:T,Albers:v,LambertConformalConic:u,SphereMercator:E,TransverseMercator:D,SpatialRelationship:{INTERSECTS:"esriSpatialRelIntersects",
CONTAINS:"esriSpatialRelContains",CROSSES:"esriSpatialRelCrosses",ENVELOPE_INTERSECTS:"esriSpatialRelEnvelopeIntersects",INDEX_INTERSECTS:"esriSpatialRelIndexIntersects",OVERLAPS:"esriSpatialRelOverlaps",TOUCHES:"esriSpatialRelTouches",WITHIN:"esriSpatialRelWithin"},GeometryType:s,SRUnit:{METER:9001,FOOT:9002,SURVEY_FOOT:9003,SURVEY_MILE:9035,KILLOMETER:9036,RADIAN:9101,DEGREE:9102},Catalog:function(a){this.url=a;var b=this;o(a,{aa:p.P},p.g,function(c){m(c,b);N(b,p.load)})},MapService:q,Layer:F,GeocodeService:Q,
GeometryService:Y,GPService:function(a){this.url=a;this.loaded=false;var b=this;o(a,{},p.g,function(c){m(c,b);b.loaded=true;i.event.trigger(b,p.load)})},GPTask:ha,RouteTask:ia,Util:C,Config:P,Projection:R,TileLayer:y,MapOverlay:B,MapType:M}})();
